/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body model module.
* @module model/Body
* @version 1.0.0
*/
export default class Body {
    /**
    * Constructs a new <code>Body</code>.
    * @alias module:model/Body
    * @class
    * @param sfile {File} form data output file
    * @param cfile {File} form data source code file
    */

    constructor(sfile, cfile) {
        
        
        this['sfile'] = sfile;
        this['cfile'] = cfile;
        
    }

    /**
    * Constructs a <code>Body</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body} obj Optional instance to populate.
    * @return {module:model/Body} The populated <code>Body</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body();
                        
            
            if (data.hasOwnProperty('sfile')) {
                obj['sfile'] = ApiClient.convertToType(data['sfile'], File);
            }
            if (data.hasOwnProperty('cfile')) {
                obj['cfile'] = ApiClient.convertToType(data['cfile'], File);
            }
        }
        return obj;
    }

    /**
    * form data output file
    * @member {File} sfile
    */
    'sfile' = undefined;
    /**
    * form data source code file
    * @member {File} cfile
    */
    'cfile' = undefined;




}
