/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsSubmissionMcq'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsSubmissionMcq'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.ModelsASubmissionMcq = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsSubmissionMcq);
  }
}(this, function(ApiClient, ModelsSubmissionMcq) {
  'use strict';

  /**
   * The ModelsASubmissionMcq model module.
   * @module model/ModelsASubmissionMcq
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsASubmissionMcq</code>.
   * @alias module:model/ModelsASubmissionMcq
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsASubmissionMcq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsASubmissionMcq} obj Optional instance to populate.
   * @return {module:model/ModelsASubmissionMcq} The populated <code>ModelsASubmissionMcq</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('submissions'))
        obj.submissions = ApiClient.convertToType(data['submissions'], [ModelsSubmissionMcq]);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ModelsSubmissionMcq>} submissions
   */
  exports.prototype.submissions = undefined;


  return exports;

}));
