/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsSignUpMode', 'model/ModelsUserType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsSignUpMode'), require('./ModelsUserType'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.ModelsUser = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsSignUpMode, root.AhanaApi.ModelsUserType);
  }
}(this, function(ApiClient, ModelsSignUpMode, ModelsUserType) {
  'use strict';




  /**
   * The ModelsUser model module.
   * @module model/ModelsUser
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsUser</code>.
   * @alias module:model/ModelsUser
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>ModelsUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsUser} obj Optional instance to populate.
   * @return {module:model/ModelsUser} The populated <code>ModelsUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('apiKey')) {
        obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Integer');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('emailNotificationEnabled')) {
        obj['emailNotificationEnabled'] = ApiClient.convertToType(data['emailNotificationEnabled'], 'Boolean');
      }
      if (data.hasOwnProperty('firebaseUID')) {
        obj['firebaseUID'] = ApiClient.convertToType(data['firebaseUID'], 'String');
      }
      if (data.hasOwnProperty('handle')) {
        obj['handle'] = ApiClient.convertToType(data['handle'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('isLocked')) {
        obj['isLocked'] = ApiClient.convertToType(data['isLocked'], 'Boolean');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('phoneNumber')) {
        obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
      }
      if (data.hasOwnProperty('rating')) {
        obj['rating'] = ApiClient.convertToType(data['rating'], 'Integer');
      }
      if (data.hasOwnProperty('signUpMode')) {
        obj['signUpMode'] = ModelsSignUpMode.constructFromObject(data['signUpMode']);
      }
      if (data.hasOwnProperty('tSize')) {
        obj['tSize'] = ApiClient.convertToType(data['tSize'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ModelsUserType.constructFromObject(data['type']);
      }
      if (data.hasOwnProperty('updated')) {
        obj['updated'] = ApiClient.convertToType(data['updated'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {String} apiKey
   */
  exports.prototype['apiKey'] = undefined;
  /**
   * @member {Integer} created
   */
  exports.prototype['created'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {Boolean} emailNotificationEnabled
   */
  exports.prototype['emailNotificationEnabled'] = undefined;
  /**
   * @member {String} firebaseUID
   */
  exports.prototype['firebaseUID'] = undefined;
  /**
   * @member {String} handle
   */
  exports.prototype['handle'] = undefined;
  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Boolean} isLocked
   */
  exports.prototype['isLocked'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} phoneNumber
   */
  exports.prototype['phoneNumber'] = undefined;
  /**
   * @member {Integer} rating
   */
  exports.prototype['rating'] = undefined;
  /**
   * @member {module:model/ModelsSignUpMode} signUpMode
   */
  exports.prototype['signUpMode'] = undefined;
  /**
   * @member {String} tSize
   */
  exports.prototype['tSize'] = undefined;
  /**
   * @member {module:model/ModelsUserType} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Integer} updated
   */
  exports.prototype['updated'] = undefined;



  return exports;
}));


