/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsMcqProblem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsMcqProblem'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.ModelsOption = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsMcqProblem);
  }
}(this, function(ApiClient, ModelsMcqProblem) {
  'use strict';

  /**
   * The ModelsOption model module.
   * @module model/ModelsOption
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsOption</code>.
   * @alias module:model/ModelsOption
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsOption} obj Optional instance to populate.
   * @return {module:model/ModelsOption} The populated <code>ModelsOption</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('mcqProblem'))
        obj.mcqProblem = ModelsMcqProblem.constructFromObject(data['mcqProblem']);
      if (data.hasOwnProperty('type(text)'))
        obj.typeText = ApiClient.convertToType(data['type(text)'], 'String');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {module:model/ModelsMcqProblem} mcqProblem
   */
  exports.prototype.mcqProblem = undefined;

  /**
   * @member {String} typeText
   */
  exports.prototype.typeText = undefined;

  /**
   * @member {Number} updated
   */
  exports.prototype.updated = undefined;


  return exports;

}));
