/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsSeries from './ModelsSeries';
import ModelsUser from './ModelsUser';

/**
* The ModelsContest model module.
* @module model/ModelsContest
* @version 1.0.0
*/
export default class ModelsContest {
    /**
    * Constructs a new <code>ModelsContest</code>.
    * @alias module:model/ModelsContest
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ModelsContest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelsContest} obj Optional instance to populate.
    * @return {module:model/ModelsContest} The populated <code>ModelsContest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsContest();
                        
            
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('organizer')) {
                obj['organizer'] = ModelsUser.constructFromObject(data['organizer']);
            }
            if (data.hasOwnProperty('series')) {
                obj['series'] = ModelsSeries.constructFromObject(data['series']);
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} created
    */
    'created' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {Number} duration
    */
    'duration' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {module:model/ModelsUser} organizer
    */
    'organizer' = undefined;
    /**
    * @member {module:model/ModelsSeries} series
    */
    'series' = undefined;
    /**
    * @member {Number} start
    */
    'start' = undefined;
    /**
    * @member {Number} updated
    */
    'updated' = undefined;




}
