/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsCodingProblem', 'model/ModelsContest', 'model/ModelsSubmissionType', 'model/ModelsVerdictType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsCodingProblem'), require('./ModelsContest'), require('./ModelsSubmissionType'), require('./ModelsVerdictType'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.ModelsSubmission = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsCodingProblem, root.AhanaApi.ModelsContest, root.AhanaApi.ModelsSubmissionType, root.AhanaApi.ModelsVerdictType);
  }
}(this, function(ApiClient, ModelsCodingProblem, ModelsContest, ModelsSubmissionType, ModelsVerdictType) {
  'use strict';

  /**
   * The ModelsSubmission model module.
   * @module model/ModelsSubmission
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsSubmission</code>.
   * @alias module:model/ModelsSubmission
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsSubmission</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsSubmission} obj Optional instance to populate.
   * @return {module:model/ModelsSubmission} The populated <code>ModelsSubmission</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contest'))
        obj.contest = ModelsContest.constructFromObject(data['contest']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('problem'))
        obj.problem = ModelsCodingProblem.constructFromObject(data['problem']);
      if (data.hasOwnProperty('type'))
        obj.type = ModelsSubmissionType.constructFromObject(data['type']);
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Number');
      if (data.hasOwnProperty('verdict'))
        obj.verdict = ModelsVerdictType.constructFromObject(data['verdict']);
    }
    return obj;
  }

  /**
   * @member {module:model/ModelsContest} contest
   */
  exports.prototype.contest = undefined;

  /**
   * @member {Number} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {module:model/ModelsCodingProblem} problem
   */
  exports.prototype.problem = undefined;

  /**
   * @member {module:model/ModelsSubmissionType} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {Number} updated
   */
  exports.prototype.updated = undefined;

  /**
   * @member {module:model/ModelsVerdictType} verdict
   */
  exports.prototype.verdict = undefined;


  return exports;

}));
