/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ModelsSubmissionResponse model module.
* @module model/ModelsSubmissionResponse
* @version 1.0.0
*/
export default class ModelsSubmissionResponse {
    /**
    * Constructs a new <code>ModelsSubmissionResponse</code>.
    * @alias module:model/ModelsSubmissionResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ModelsSubmissionResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelsSubmissionResponse} obj Optional instance to populate.
    * @return {module:model/ModelsSubmissionResponse} The populated <code>ModelsSubmissionResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsSubmissionResponse();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('verdict')) {
                obj['verdict'] = ApiClient.convertToType(data['verdict'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {String} message
    */
    'message' = undefined;
    /**
    * @member {String} verdict
    */
    'verdict' = undefined;




}
