/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsSeries', 'model/ModelsUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsSeries'), require('./ModelsUser'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.ModelsContest = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsSeries, root.AhanaApi.ModelsUser);
  }
}(this, function(ApiClient, ModelsSeries, ModelsUser) {
  'use strict';




  /**
   * The ModelsContest model module.
   * @module model/ModelsContest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsContest</code>.
   * @alias module:model/ModelsContest
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>ModelsContest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsContest} obj Optional instance to populate.
   * @return {module:model/ModelsContest} The populated <code>ModelsContest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Integer');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Integer');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('organizer')) {
        obj['organizer'] = ModelsUser.constructFromObject(data['organizer']);
      }
      if (data.hasOwnProperty('series')) {
        obj['series'] = ModelsSeries.constructFromObject(data['series']);
      }
      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'Integer');
      }
      if (data.hasOwnProperty('updated')) {
        obj['updated'] = ApiClient.convertToType(data['updated'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} created
   */
  exports.prototype['created'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Integer} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/ModelsUser} organizer
   */
  exports.prototype['organizer'] = undefined;
  /**
   * @member {module:model/ModelsSeries} series
   */
  exports.prototype['series'] = undefined;
  /**
   * @member {Integer} start
   */
  exports.prototype['start'] = undefined;
  /**
   * @member {Integer} updated
   */
  exports.prototype['updated'] = undefined;



  return exports;
}));


