/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ModelsSignUpMode model module.
* @module model/ModelsSignUpMode
* @version 1.0.0
*/
export default class ModelsSignUpMode {
    /**
    * Constructs a new <code>ModelsSignUpMode</code>.
    * @alias module:model/ModelsSignUpMode
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ModelsSignUpMode</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelsSignUpMode} obj Optional instance to populate.
    * @return {module:model/ModelsSignUpMode} The populated <code>ModelsSignUpMode</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsSignUpMode();
                        
            
        }
        return obj;
    }





}
