/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsContest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsContest'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.ModelsCodingProblem = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsContest);
  }
}(this, function(ApiClient, ModelsContest) {
  'use strict';

  /**
   * The ModelsCodingProblem model module.
   * @module model/ModelsCodingProblem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsCodingProblem</code>.
   * @alias module:model/ModelsCodingProblem
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsCodingProblem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsCodingProblem} obj Optional instance to populate.
   * @return {module:model/ModelsCodingProblem} The populated <code>ModelsCodingProblem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('constraints'))
        obj.constraints = ApiClient.convertToType(data['constraints'], 'String');
      if (data.hasOwnProperty('contest'))
        obj.contest = ModelsContest.constructFromObject(data['contest']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('editorial'))
        obj.editorial = ApiClient.convertToType(data['editorial'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('inputFormat'))
        obj.inputFormat = ApiClient.convertToType(data['inputFormat'], 'String');
      if (data.hasOwnProperty('maxScore'))
        obj.maxScore = ApiClient.convertToType(data['maxScore'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('outputFormat'))
        obj.outputFormat = ApiClient.convertToType(data['outputFormat'], 'String');
      if (data.hasOwnProperty('sampleExplanation'))
        obj.sampleExplanation = ApiClient.convertToType(data['sampleExplanation'], 'String');
      if (data.hasOwnProperty('sampleInput'))
        obj.sampleInput = ApiClient.convertToType(data['sampleInput'], 'String');
      if (data.hasOwnProperty('sampleOutput'))
        obj.sampleOutput = ApiClient.convertToType(data['sampleOutput'], 'String');
      if (data.hasOwnProperty('statement'))
        obj.statement = ApiClient.convertToType(data['statement'], 'String');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} constraints
   */
  exports.prototype.constraints = undefined;

  /**
   * @member {module:model/ModelsContest} contest
   */
  exports.prototype.contest = undefined;

  /**
   * @member {Number} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {String} editorial
   */
  exports.prototype.editorial = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} inputFormat
   */
  exports.prototype.inputFormat = undefined;

  /**
   * @member {Number} maxScore
   */
  exports.prototype.maxScore = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} outputFormat
   */
  exports.prototype.outputFormat = undefined;

  /**
   * @member {String} sampleExplanation
   */
  exports.prototype.sampleExplanation = undefined;

  /**
   * @member {String} sampleInput
   */
  exports.prototype.sampleInput = undefined;

  /**
   * @member {String} sampleOutput
   */
  exports.prototype.sampleOutput = undefined;

  /**
   * @member {String} statement
   */
  exports.prototype.statement = undefined;

  /**
   * @member {Number} updated
   */
  exports.prototype.updated = undefined;


  return exports;

}));
