/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsCodingProblem from './ModelsCodingProblem';
import ModelsContest from './ModelsContest';
import ModelsUser from './ModelsUser';

/**
* The ModelsSubmissionDeadline model module.
* @module model/ModelsSubmissionDeadline
* @version 1.0.0
*/
export default class ModelsSubmissionDeadline {
    /**
    * Constructs a new <code>ModelsSubmissionDeadline</code>.
    * @alias module:model/ModelsSubmissionDeadline
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ModelsSubmissionDeadline</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelsSubmissionDeadline} obj Optional instance to populate.
    * @return {module:model/ModelsSubmissionDeadline} The populated <code>ModelsSubmissionDeadline</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsSubmissionDeadline();
                        
            
            if (data.hasOwnProperty('contest')) {
                obj['contest'] = ModelsContest.constructFromObject(data['contest']);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Number');
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('problem')) {
                obj['problem'] = ModelsCodingProblem.constructFromObject(data['problem']);
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Number');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ModelsUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ModelsContest} contest
    */
    'contest' = undefined;
    /**
    * @member {Number} created
    */
    'created' = undefined;
    /**
    * @member {Number} deadline
    */
    'deadline' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {module:model/ModelsCodingProblem} problem
    */
    'problem' = undefined;
    /**
    * @member {Number} updated
    */
    'updated' = undefined;
    /**
    * @member {module:model/ModelsUser} user
    */
    'user' = undefined;




}
