/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsContest', 'model/ModelsMcqProblemType', 'model/ModelsOption'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsContest'), require('./ModelsMcqProblemType'), require('./ModelsOption'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.ModelsMcqProblem = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsContest, root.AhanaApi.ModelsMcqProblemType, root.AhanaApi.ModelsOption);
  }
}(this, function(ApiClient, ModelsContest, ModelsMcqProblemType, ModelsOption) {
  'use strict';

  /**
   * The ModelsMcqProblem model module.
   * @module model/ModelsMcqProblem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsMcqProblem</code>.
   * @alias module:model/ModelsMcqProblem
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsMcqProblem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsMcqProblem} obj Optional instance to populate.
   * @return {module:model/ModelsMcqProblem} The populated <code>ModelsMcqProblem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contest'))
        obj.contest = ModelsContest.constructFromObject(data['contest']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('imageUrl'))
        obj.imageUrl = ApiClient.convertToType(data['imageUrl'], 'String');
      if (data.hasOwnProperty('maxScore'))
        obj.maxScore = ApiClient.convertToType(data['maxScore'], 'Number');
      if (data.hasOwnProperty('options'))
        obj.options = ApiClient.convertToType(data['options'], [ModelsOption]);
      if (data.hasOwnProperty('question'))
        obj.question = ApiClient.convertToType(data['question'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ModelsMcqProblemType.constructFromObject(data['type']);
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Number');
    }
    return obj;
  }

  /**
   * @member {module:model/ModelsContest} contest
   */
  exports.prototype.contest = undefined;

  /**
   * @member {Number} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} imageUrl
   */
  exports.prototype.imageUrl = undefined;

  /**
   * @member {Number} maxScore
   */
  exports.prototype.maxScore = undefined;

  /**
   * @member {Array.<module:model/ModelsOption>} options
   */
  exports.prototype.options = undefined;

  /**
   * @member {String} question
   */
  exports.prototype.question = undefined;

  /**
   * @member {module:model/ModelsMcqProblemType} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {Number} updated
   */
  exports.prototype.updated = undefined;


  return exports;

}));
