/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsContest', 'model/ModelsMcqType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsContest'), require('./ModelsMcqType'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.ModelsMcqProblem = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsContest, root.AhanaApi.ModelsMcqType);
  }
}(this, function(ApiClient, ModelsContest, ModelsMcqType) {
  'use strict';

  /**
   * The ModelsMcqProblem model module.
   * @module model/ModelsMcqProblem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsMcqProblem</code>.
   * @alias module:model/ModelsMcqProblem
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsMcqProblem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsMcqProblem} obj Optional instance to populate.
   * @return {module:model/ModelsMcqProblem} The populated <code>ModelsMcqProblem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contest'))
        obj.contest = ModelsContest.constructFromObject(data['contest']);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('optionFour'))
        obj.optionFour = ApiClient.convertToType(data['optionFour'], 'String');
      if (data.hasOwnProperty('optionOne'))
        obj.optionOne = ApiClient.convertToType(data['optionOne'], 'String');
      if (data.hasOwnProperty('optionThree'))
        obj.optionThree = ApiClient.convertToType(data['optionThree'], 'String');
      if (data.hasOwnProperty('optionTwo'))
        obj.optionTwo = ApiClient.convertToType(data['optionTwo'], 'String');
      if (data.hasOwnProperty('statement'))
        obj.statement = ApiClient.convertToType(data['statement'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ModelsMcqType.constructFromObject(data['type']);
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Number');
    }
    return obj;
  }

  /**
   * @member {module:model/ModelsContest} contest
   */
  exports.prototype.contest = undefined;

  /**
   * @member {Number} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} optionFour
   */
  exports.prototype.optionFour = undefined;

  /**
   * @member {String} optionOne
   */
  exports.prototype.optionOne = undefined;

  /**
   * @member {String} optionThree
   */
  exports.prototype.optionThree = undefined;

  /**
   * @member {String} optionTwo
   */
  exports.prototype.optionTwo = undefined;

  /**
   * @member {String} statement
   */
  exports.prototype.statement = undefined;

  /**
   * @member {module:model/ModelsMcqType} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {Number} updated
   */
  exports.prototype.updated = undefined;


  return exports;

}));
