/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ModelsSubmissionType model module.
* @module model/ModelsSubmissionType
* @version 1.0.0
*/
export default class ModelsSubmissionType {
    /**
    * Constructs a new <code>ModelsSubmissionType</code>.
    * @alias module:model/ModelsSubmissionType
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ModelsSubmissionType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelsSubmissionType} obj Optional instance to populate.
    * @return {module:model/ModelsSubmissionType} The populated <code>ModelsSubmissionType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsSubmissionType();
                        
            
        }
        return obj;
    }





}
