/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsSignUpMode from './ModelsSignUpMode';
import ModelsUserType from './ModelsUserType';

/**
* The ModelsUser model module.
* @module model/ModelsUser
* @version 1.0.0
*/
export default class ModelsUser {
    /**
    * Constructs a new <code>ModelsUser</code>.
    * @alias module:model/ModelsUser
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ModelsUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelsUser} obj Optional instance to populate.
    * @return {module:model/ModelsUser} The populated <code>ModelsUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsUser();
                        
            
            if (data.hasOwnProperty('apiKey')) {
                obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Number');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('emailNotificationEnabled')) {
                obj['emailNotificationEnabled'] = ApiClient.convertToType(data['emailNotificationEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('firebaseUID')) {
                obj['firebaseUID'] = ApiClient.convertToType(data['firebaseUID'], 'String');
            }
            if (data.hasOwnProperty('handle')) {
                obj['handle'] = ApiClient.convertToType(data['handle'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('isLocked')) {
                obj['isLocked'] = ApiClient.convertToType(data['isLocked'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('signUpMode')) {
                obj['signUpMode'] = ModelsSignUpMode.constructFromObject(data['signUpMode']);
            }
            if (data.hasOwnProperty('tSize')) {
                obj['tSize'] = ApiClient.convertToType(data['tSize'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ModelsUserType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} apiKey
    */
    'apiKey' = undefined;
    /**
    * @member {Number} created
    */
    'created' = undefined;
    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {Boolean} emailNotificationEnabled
    */
    'emailNotificationEnabled' = undefined;
    /**
    * @member {String} firebaseUID
    */
    'firebaseUID' = undefined;
    /**
    * @member {String} handle
    */
    'handle' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {Boolean} isLocked
    */
    'isLocked' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} phoneNumber
    */
    'phoneNumber' = undefined;
    /**
    * @member {Number} rating
    */
    'rating' = undefined;
    /**
    * @member {module:model/ModelsSignUpMode} signUpMode
    */
    'signUpMode' = undefined;
    /**
    * @member {String} tSize
    */
    'tSize' = undefined;
    /**
    * @member {module:model/ModelsUserType} type
    */
    'type' = undefined;
    /**
    * @member {Number} updated
    */
    'updated' = undefined;




}
