/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsContest from './ModelsContest';

/**
* The ModelsCodingProblem model module.
* @module model/ModelsCodingProblem
* @version 1.0.0
*/
export default class ModelsCodingProblem {
    /**
    * Constructs a new <code>ModelsCodingProblem</code>.
    * @alias module:model/ModelsCodingProblem
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ModelsCodingProblem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelsCodingProblem} obj Optional instance to populate.
    * @return {module:model/ModelsCodingProblem} The populated <code>ModelsCodingProblem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsCodingProblem();
                        
            
            if (data.hasOwnProperty('constraints')) {
                obj['constraints'] = ApiClient.convertToType(data['constraints'], 'String');
            }
            if (data.hasOwnProperty('contest')) {
                obj['contest'] = ModelsContest.constructFromObject(data['contest']);
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Number');
            }
            if (data.hasOwnProperty('editorial')) {
                obj['editorial'] = ApiClient.convertToType(data['editorial'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('inputFormat')) {
                obj['inputFormat'] = ApiClient.convertToType(data['inputFormat'], 'String');
            }
            if (data.hasOwnProperty('maxScore')) {
                obj['maxScore'] = ApiClient.convertToType(data['maxScore'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('outputFormat')) {
                obj['outputFormat'] = ApiClient.convertToType(data['outputFormat'], 'String');
            }
            if (data.hasOwnProperty('sampleExplanation')) {
                obj['sampleExplanation'] = ApiClient.convertToType(data['sampleExplanation'], 'String');
            }
            if (data.hasOwnProperty('sampleInput')) {
                obj['sampleInput'] = ApiClient.convertToType(data['sampleInput'], 'String');
            }
            if (data.hasOwnProperty('sampleOutput')) {
                obj['sampleOutput'] = ApiClient.convertToType(data['sampleOutput'], 'String');
            }
            if (data.hasOwnProperty('statement')) {
                obj['statement'] = ApiClient.convertToType(data['statement'], 'String');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} constraints
    */
    'constraints' = undefined;
    /**
    * @member {module:model/ModelsContest} contest
    */
    'contest' = undefined;
    /**
    * @member {Number} created
    */
    'created' = undefined;
    /**
    * @member {String} editorial
    */
    'editorial' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {String} inputFormat
    */
    'inputFormat' = undefined;
    /**
    * @member {Number} maxScore
    */
    'maxScore' = undefined;
    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} outputFormat
    */
    'outputFormat' = undefined;
    /**
    * @member {String} sampleExplanation
    */
    'sampleExplanation' = undefined;
    /**
    * @member {String} sampleInput
    */
    'sampleInput' = undefined;
    /**
    * @member {String} sampleOutput
    */
    'sampleOutput' = undefined;
    /**
    * @member {String} statement
    */
    'statement' = undefined;
    /**
    * @member {Number} updated
    */
    'updated' = undefined;




}
