/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsSubmissionDeadline from './ModelsSubmissionDeadline';

/**
* The ModelsRSubmissionDeadline model module.
* @module model/ModelsRSubmissionDeadline
* @version 1.0.0
*/
export default class ModelsRSubmissionDeadline {
    /**
    * Constructs a new <code>ModelsRSubmissionDeadline</code>.
    * @alias module:model/ModelsRSubmissionDeadline
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ModelsRSubmissionDeadline</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelsRSubmissionDeadline} obj Optional instance to populate.
    * @return {module:model/ModelsRSubmissionDeadline} The populated <code>ModelsRSubmissionDeadline</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsRSubmissionDeadline();
                        
            
            if (data.hasOwnProperty('inputFileDownloaded')) {
                obj['inputFileDownloaded'] = ApiClient.convertToType(data['inputFileDownloaded'], 'Boolean');
            }
            if (data.hasOwnProperty('inputFileUrl')) {
                obj['inputFileUrl'] = ApiClient.convertToType(data['inputFileUrl'], 'String');
            }
            if (data.hasOwnProperty('submissionDeadline')) {
                obj['submissionDeadline'] = ModelsSubmissionDeadline.constructFromObject(data['submissionDeadline']);
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} inputFileDownloaded
    */
    'inputFileDownloaded' = undefined;
    /**
    * @member {String} inputFileUrl
    */
    'inputFileUrl' = undefined;
    /**
    * @member {module:model/ModelsSubmissionDeadline} submissionDeadline
    */
    'submissionDeadline' = undefined;




}
