/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ModelsCodingProblem from '../model/ModelsCodingProblem';
import ModelsRSubmissionDeadline from '../model/ModelsRSubmissionDeadline';

/**
* CodingProblems service.
* @module api/CodingProblemsApi
* @version 1.0.0
*/
export default class CodingProblemsApi {

    /**
    * Constructs a new CodingProblemsApi. 
    * @alias module:api/CodingProblemsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the codingProblemControllerDownloadInputFile operation.
     * @callback module:api/CodingProblemsApi~codingProblemControllerDownloadInputFileCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Input File only if the submission deadline for the user is on or the contest ended
     * @param {module:api/CodingProblemsApi~codingProblemControllerDownloadInputFileCallback} callback The callback function, accepting three arguments: error, data, response
     */
    codingProblemControllerDownloadInputFile(key, pid, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'key': key,
        'pid': pid
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/coding-problems/in/download', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the codingProblemControllerGetCodingProblemById operation.
     * @callback module:api/CodingProblemsApi~codingProblemControllerGetCodingProblemByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsCodingProblem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get CodingProblem by Id
     * @param {module:api/CodingProblemsApi~codingProblemControllerGetCodingProblemByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsCodingProblem}
     */
    codingProblemControllerGetCodingProblemById(problemId, callback) {
      let postBody = null;

      let pathParams = {
        'problemId': problemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelsCodingProblem;

      return this.apiClient.callApi(
        '/coding-problems/{problemId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the codingProblemControllerGetCodingProblemsByContest operation.
     * @callback module:api/CodingProblemsApi~codingProblemControllerGetCodingProblemsByContestCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsCodingProblem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All CodingProblems By Contest Id
     * @param {module:api/CodingProblemsApi~codingProblemControllerGetCodingProblemsByContestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsCodingProblem>}
     */
    codingProblemControllerGetCodingProblemsByContest(cid, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'cid': cid
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ModelsCodingProblem];

      return this.apiClient.callApi(
        '/coding-problems/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the codingProblemControllerInitSubmissionDeadline operation.
     * @callback module:api/CodingProblemsApi~codingProblemControllerInitSubmissionDeadlineCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsRSubmissionDeadline} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Input File and create a submission deadline for the user
     * @param {module:api/CodingProblemsApi~codingProblemControllerInitSubmissionDeadlineCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsRSubmissionDeadline}
     */
    codingProblemControllerInitSubmissionDeadline(xUserApiKey, pid, callback) {
      let postBody = null;

      let pathParams = {
        'pid': pid
      };
      let queryParams = {
      };
      let headerParams = {
        'X-User-ApiKey': xUserApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelsRSubmissionDeadline;

      return this.apiClient.callApi(
        '/coding-problems/{pid}/init', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
