/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsContest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ModelsContest'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.ContestsApi = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsContest);
  }
}(this, function(ApiClient, ModelsContest) {
  'use strict';

  /**
   * Contests service.
   * @module api/ContestsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ContestsApi. 
   * @alias module:api/ContestsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the contestControllerGetContest operation.
     * @callback module:api/ContestsApi~contestControllerGetContestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsContest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Contest by id
     * @param {Integer} contestId the ContestId you want to get
     * @param {module:api/ContestsApi~contestControllerGetContestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsContest}
     */
    this.contestControllerGetContest = function(contestId, callback) {
      var postBody = null;

      // verify the required parameter 'contestId' is set
      if (contestId == undefined || contestId == null) {
        throw "Missing the required parameter 'contestId' when calling contestControllerGetContest";
      }


      var pathParams = {
        'contestId': contestId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsContest;

      return this.apiClient.callApi(
        '/contests/{contestId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the contestControllerGetContestsBySeries operation.
     * @callback module:api/ContestsApi~contestControllerGetContestsBySeriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsContest>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Contests By Series Id
     * @param {Integer} sid series id
     * @param {module:api/ContestsApi~contestControllerGetContestsBySeriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsContest>}
     */
    this.contestControllerGetContestsBySeries = function(sid, callback) {
      var postBody = null;

      // verify the required parameter 'sid' is set
      if (sid == undefined || sid == null) {
        throw "Missing the required parameter 'sid' when calling contestControllerGetContestsBySeries";
      }


      var pathParams = {
      };
      var queryParams = {
        'sid': sid
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsContest];

      return this.apiClient.callApi(
        '/contests/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the contestControllerRegisterForContest operation.
     * @callback module:api/ContestsApi~contestControllerRegisterForContestCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Register for an upcoming contest
     * @param {String} xUserApiKey User API Key
     * @param {Integer} contestId the contest id you want to register for
     * @param {module:api/ContestsApi~contestControllerRegisterForContestCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.contestControllerRegisterForContest = function(xUserApiKey, contestId, callback) {
      var postBody = null;

      // verify the required parameter 'xUserApiKey' is set
      if (xUserApiKey == undefined || xUserApiKey == null) {
        throw "Missing the required parameter 'xUserApiKey' when calling contestControllerRegisterForContest";
      }

      // verify the required parameter 'contestId' is set
      if (contestId == undefined || contestId == null) {
        throw "Missing the required parameter 'contestId' when calling contestControllerRegisterForContest";
      }


      var pathParams = {
        'contestId': contestId
      };
      var queryParams = {
      };
      var headerParams = {
        'X-User-ApiKey': xUserApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/contests/{contestId}/register', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
