/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ModelsContest from '../model/ModelsContest';
import ModelsContestResponse from '../model/ModelsContestResponse';

/**
* Contests service.
* @module api/ContestsApi
* @version 1.0.0
*/
export default class ContestsApi {

    /**
    * Constructs a new ContestsApi. 
    * @alias module:api/ContestsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the contestControllerGetContest operation.
     * @callback module:api/ContestsApi~contestControllerGetContestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsContestResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Contest by id
     * @param {module:api/ContestsApi~contestControllerGetContestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsContestResponse}
     */
    contestControllerGetContest(contestId, callback) {
      let postBody = null;

      let pathParams = {
        'contestId': contestId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelsContestResponse;

      return this.apiClient.callApi(
        '/contests/{contestId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the contestControllerGetContestsBySeries operation.
     * @callback module:api/ContestsApi~contestControllerGetContestsBySeriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsContest>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Contests By Series Id
     * @param {module:api/ContestsApi~contestControllerGetContestsBySeriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsContest>}
     */
    contestControllerGetContestsBySeries(sid, callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'sid': sid
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ModelsContest];

      return this.apiClient.callApi(
        '/contests/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the contestControllerRegisterForContest operation.
     * @callback module:api/ContestsApi~contestControllerRegisterForContestCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Register for an upcoming contest
     * @param {module:api/ContestsApi~contestControllerRegisterForContestCallback} callback The callback function, accepting three arguments: error, data, response
     */
    contestControllerRegisterForContest(xUserApiKey, contestId, callback) {
      let postBody = null;

      let pathParams = {
        'contestId': contestId
      };
      let queryParams = {
      };
      let headerParams = {
        'X-User-ApiKey': xUserApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/contests/{contestId}/register', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
