/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsMcqProblem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ModelsMcqProblem'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.McqProblemsApi = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsMcqProblem);
  }
}(this, function(ApiClient, ModelsMcqProblem) {
  'use strict';

  /**
   * McqProblems service.
   * @module api/McqProblemsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new McqProblemsApi. 
   * @alias module:api/McqProblemsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the mcqProblemControllerGetMcqProblemsByContest operation.
     * @callback module:api/McqProblemsApi~mcqProblemControllerGetMcqProblemsByContestCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsMcqProblem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All McqProblems By Contest Id
     * @param {Number} cid contest id
     * @param {module:api/McqProblemsApi~mcqProblemControllerGetMcqProblemsByContestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsMcqProblem>}
     */
    this.mcqProblemControllerGetMcqProblemsByContest = function(cid, callback) {
      var postBody = null;

      // verify the required parameter 'cid' is set
      if (cid === undefined || cid === null) {
        throw new Error("Missing the required parameter 'cid' when calling mcqProblemControllerGetMcqProblemsByContest");
      }


      var pathParams = {
      };
      var queryParams = {
        'cid': cid,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsMcqProblem];

      return this.apiClient.callApi(
        '/mcq-problems/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
