/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import ModelsSeries from '../model/ModelsSeries';

/**
* Series service.
* @module api/SeriesApi
* @version 1.0.0
*/
export default class SeriesApi {

    /**
    * Constructs a new SeriesApi. 
    * @alias module:api/SeriesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the seriesControllerGetAllSeries operation.
     * @callback module:api/SeriesApi~seriesControllerGetAllSeriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsSeries>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Series
     * @param {module:api/SeriesApi~seriesControllerGetAllSeriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsSeries>}
     */
    seriesControllerGetAllSeries(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ModelsSeries];

      return this.apiClient.callApi(
        '/series/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the seriesControllerGetSeries operation.
     * @callback module:api/SeriesApi~seriesControllerGetSeriesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsSeries} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Series by id
     * @param {module:api/SeriesApi~seriesControllerGetSeriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsSeries}
     */
    seriesControllerGetSeries(sid, callback) {
      let postBody = null;

      let pathParams = {
        'sid': sid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelsSeries;

      return this.apiClient.callApi(
        '/series/{sid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
