/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsEUser', 'model/ModelsUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ModelsEUser'), require('../model/ModelsUser'));
  } else {
    // Browser globals (root is window)
    if (!root.AhanaApi) {
      root.AhanaApi = {};
    }
    root.AhanaApi.UsersApi = factory(root.AhanaApi.ApiClient, root.AhanaApi.ModelsEUser, root.AhanaApi.ModelsUser);
  }
}(this, function(ApiClient, ModelsEUser, ModelsUser) {
  'use strict';

  /**
   * Users service.
   * @module api/UsersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new UsersApi. 
   * @alias module:api/UsersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the userControllerCreateUser operation.
     * @callback module:api/UsersApi~userControllerCreateUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsUser} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create New User
     * @param {module:model/ModelsEUser} body User details
     * @param {String} xToken Firebase token
     * @param {module:api/UsersApi~userControllerCreateUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsUser}
     */
    this.userControllerCreateUser = function(body, xToken, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling userControllerCreateUser");
      }

      // verify the required parameter 'xToken' is set
      if (xToken === undefined || xToken === null) {
        throw new Error("Missing the required parameter 'xToken' when calling userControllerCreateUser");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Token': xToken
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsUser;

      return this.apiClient.callApi(
        '/users/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the userControllerGetUser operation.
     * @callback module:api/UsersApi~userControllerGetUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsUser} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Existing User
     * @param {String} xToken Firebase token
     * @param {String} firebaseUid the firebase uid of the user you need to fetch
     * @param {module:api/UsersApi~userControllerGetUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsUser}
     */
    this.userControllerGetUser = function(xToken, firebaseUid, callback) {
      var postBody = null;

      // verify the required parameter 'xToken' is set
      if (xToken === undefined || xToken === null) {
        throw new Error("Missing the required parameter 'xToken' when calling userControllerGetUser");
      }

      // verify the required parameter 'firebaseUid' is set
      if (firebaseUid === undefined || firebaseUid === null) {
        throw new Error("Missing the required parameter 'firebaseUid' when calling userControllerGetUser");
      }


      var pathParams = {
        'firebaseUid': firebaseUid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Token': xToken
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsUser;

      return this.apiClient.callApi(
        '/users/{firebaseUid}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
