/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AhanaApi);
  }
}(this, function(expect, AhanaApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsContestResponse', function() {
      beforeEach(function() {
        instance = new AhanaApi.ModelsContestResponse();
      });

      it('should create an instance of ModelsContestResponse', function() {
        // TODO: update the code to test ModelsContestResponse
        expect(instance).to.be.a(AhanaApi.ModelsContestResponse);
      });

      it('should have the property contest (base name: "contest")', function() {
        // TODO: update the code to test the property contest
        expect(instance).to.have.property('contest');
        // expect(instance.contest).to.be(expectedValueLiteral);
      });

      it('should have the property userRegistered (base name: "userRegistered")', function() {
        // TODO: update the code to test the property userRegistered
        expect(instance).to.have.property('userRegistered');
        // expect(instance.userRegistered).to.be(expectedValueLiteral);
      });

    });
  });

}));
