/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AhanaApi);
  }
}(this, function(expect, AhanaApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsRSubmissionDeadline', function() {
      beforeEach(function() {
        instance = new AhanaApi.ModelsRSubmissionDeadline();
      });

      it('should create an instance of ModelsRSubmissionDeadline', function() {
        // TODO: update the code to test ModelsRSubmissionDeadline
        expect(instance).to.be.a(AhanaApi.ModelsRSubmissionDeadline);
      });

      it('should have the property inputFileDownloaded (base name: "inputFileDownloaded")', function() {
        // TODO: update the code to test the property inputFileDownloaded
        expect(instance).to.have.property('inputFileDownloaded');
        // expect(instance.inputFileDownloaded).to.be(expectedValueLiteral);
      });

      it('should have the property inputFileUrl (base name: "inputFileUrl")', function() {
        // TODO: update the code to test the property inputFileUrl
        expect(instance).to.have.property('inputFileUrl');
        // expect(instance.inputFileUrl).to.be(expectedValueLiteral);
      });

      it('should have the property submissionDeadline (base name: "submissionDeadline")', function() {
        // TODO: update the code to test the property submissionDeadline
        expect(instance).to.have.property('submissionDeadline');
        // expect(instance.submissionDeadline).to.be(expectedValueLiteral);
      });

    });
  });

}));
