/**
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AhanaApi);
  }
}(this, function(expect, AhanaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AhanaApi.ModelsUser();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModelsUser', function() {
    it('should create an instance of ModelsUser', function() {
      // uncomment below and update the code to test ModelsUser
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be.a(AhanaApi.ModelsUser);
    });

    it('should have the property apiKey (base name: "apiKey")', function() {
      // uncomment below and update the code to test the property apiKey
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property emailNotificationEnabled (base name: "emailNotificationEnabled")', function() {
      // uncomment below and update the code to test the property emailNotificationEnabled
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property firebaseUID (base name: "firebaseUID")', function() {
      // uncomment below and update the code to test the property firebaseUID
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property handle (base name: "handle")', function() {
      // uncomment below and update the code to test the property handle
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property isLocked (base name: "isLocked")', function() {
      // uncomment below and update the code to test the property isLocked
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phoneNumber")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property rating (base name: "rating")', function() {
      // uncomment below and update the code to test the property rating
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property signUpMode (base name: "signUpMode")', function() {
      // uncomment below and update the code to test the property signUpMode
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property tSize (base name: "tSize")', function() {
      // uncomment below and update the code to test the property tSize
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

    it('should have the property updated (base name: "updated")', function() {
      // uncomment below and update the code to test the property updated
      //var instane = new AhanaApi.ModelsUser();
      //expect(instance).to.be();
    });

  });

}));
