/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mail@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AhanaApi);
  }
}(this, function(expect, AhanaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AhanaApi.ProblemsApi();
  });

  describe('(package)', function() {
    describe('ProblemsApi', function() {
      describe('problemControllerGetInputFileAndInitSubmissionDeadline', function() {
        it('should call problemControllerGetInputFileAndInitSubmissionDeadline successfully', function(done) {
          // TODO: uncomment, update parameter values for problemControllerGetInputFileAndInitSubmissionDeadline call
          /*
          var xUserApiKey = "xUserApiKey_example";
          var pid = 789;

          instance.problemControllerGetInputFileAndInitSubmissionDeadline(xUserApiKey, pid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
