/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AhanaApi);
  }
}(this, function(expect, AhanaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AhanaApi.SeriesApi();
  });

  describe('(package)', function() {
    describe('SeriesApi', function() {
      describe('seriesControllerGetAllSeries', function() {
        it('should call seriesControllerGetAllSeries successfully', function(done) {
          // TODO: uncomment seriesControllerGetAllSeries call and complete the assertions
          /*

          instance.seriesControllerGetAllSeries(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(AhanaApi.ModelsSeries);
              expect(data.created).to.be.a('number');
              expect(data.created).to.be("0");
              expect(data.description).to.be.a('string');
              expect(data.description).to.be("");
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.logoUrl).to.be.a('string');
              expect(data.logoUrl).to.be("");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.updated).to.be.a('number');
              expect(data.updated).to.be("0");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('seriesControllerGetSeries', function() {
        it('should call seriesControllerGetSeries successfully', function(done) {
          // TODO: uncomment, update parameter values for seriesControllerGetSeries call and complete the assertions
          /*
          var sid = 789;

          instance.seriesControllerGetSeries(sid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AhanaApi.ModelsSeries);
            expect(data.created).to.be.a('number');
            expect(data.created).to.be("0");
            expect(data.description).to.be.a('string');
            expect(data.description).to.be("");
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.logoUrl).to.be.a('string');
            expect(data.logoUrl).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.updated).to.be.a('number');
            expect(data.updated).to.be("0");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
