/*
 * Ahana API
 * Ahana Web Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ahana@karngyan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AhanaApi);
  }
}(this, function(expect, AhanaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AhanaApi.SubmissionsApi();
  });

  describe('(package)', function() {
    describe('SubmissionsApi', function() {
      describe('submissionControllerGetAllUserSubmissionsByContest', function() {
        it('should call submissionControllerGetAllUserSubmissionsByContest successfully', function(done) {
          // TODO: uncomment, update parameter values for submissionControllerGetAllUserSubmissionsByContest call and complete the assertions
          /*
          var xUserApiKey = "xUserApiKey_example";
          var cid = 789;

          instance.submissionControllerGetAllUserSubmissionsByContest(xUserApiKey, cid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(AhanaApi.ModelsSubmission);
              expect(data.contest).to.be.a(AhanaApi.ModelsContest);
                    expect(data.contest.created).to.be.a('number');
                expect(data.contest.created).to.be("0");
                expect(data.contest.description).to.be.a('string');
                expect(data.contest.description).to.be("");
                expect(data.contest.duration).to.be.a('number');
                expect(data.contest.duration).to.be("0");
                expect(data.contest.id).to.be.a('number');
                expect(data.contest.id).to.be("0");
                expect(data.contest.name).to.be.a('string');
                expect(data.contest.name).to.be("");
                expect(data.contest.organizer).to.be.a(AhanaApi.ModelsUser);
                      expect(data.contest.organizer.apiKey).to.be.a('string');
                  expect(data.contest.organizer.apiKey).to.be("");
                  expect(data.contest.organizer.created).to.be.a('number');
                  expect(data.contest.organizer.created).to.be("0");
                  expect(data.contest.organizer.email).to.be.a('string');
                  expect(data.contest.organizer.email).to.be("");
                  expect(data.contest.organizer.emailNotificationEnabled).to.be.a('boolean');
                  expect(data.contest.organizer.emailNotificationEnabled).to.be(false);
                  expect(data.contest.organizer.firebaseUID).to.be.a('string');
                  expect(data.contest.organizer.firebaseUID).to.be("");
                  expect(data.contest.organizer.handle).to.be.a('string');
                  expect(data.contest.organizer.handle).to.be("");
                  expect(data.contest.organizer.id).to.be.a('number');
                  expect(data.contest.organizer.id).to.be("0");
                  expect(data.contest.organizer.isLocked).to.be.a('boolean');
                  expect(data.contest.organizer.isLocked).to.be(false);
                  expect(data.contest.organizer.name).to.be.a('string');
                  expect(data.contest.organizer.name).to.be("");
                  expect(data.contest.organizer.phoneNumber).to.be.a('string');
                  expect(data.contest.organizer.phoneNumber).to.be("");
                  expect(data.contest.organizer.rating).to.be.a('number');
                  expect(data.contest.organizer.rating).to.be("0");
                  expect(data.contest.organizer.signUpMode).to.be.a(AhanaApi.ModelsSignUpMode);
                      expect(data.contest.organizer.tSize).to.be.a('string');
                  expect(data.contest.organizer.tSize).to.be("");
                  expect(data.contest.organizer.type).to.be.a(AhanaApi.ModelsUserType);
                      expect(data.contest.organizer.updated).to.be.a('number');
                  expect(data.contest.organizer.updated).to.be("0");
                expect(data.contest.series).to.be.a(AhanaApi.ModelsSeries);
                      expect(data.contest.series.created).to.be.a('number');
                  expect(data.contest.series.created).to.be("0");
                  expect(data.contest.series.description).to.be.a('string');
                  expect(data.contest.series.description).to.be("");
                  expect(data.contest.series.id).to.be.a('number');
                  expect(data.contest.series.id).to.be("0");
                  expect(data.contest.series.logoUrl).to.be.a('string');
                  expect(data.contest.series.logoUrl).to.be("");
                  expect(data.contest.series.name).to.be.a('string');
                  expect(data.contest.series.name).to.be("");
                  expect(data.contest.series.updated).to.be.a('number');
                  expect(data.contest.series.updated).to.be("0");
                expect(data.contest.start).to.be.a('number');
                expect(data.contest.start).to.be("0");
                expect(data.contest.updated).to.be.a('number');
                expect(data.contest.updated).to.be("0");
              expect(data.created).to.be.a('number');
              expect(data.created).to.be("0");
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.problem).to.be.a(AhanaApi.ModelsCodingProblem);
                    expect(data.problem.constraints).to.be.a('string');
                expect(data.problem.constraints).to.be("");
                expect(data.problem.contest).to.be.a(AhanaApi.ModelsContest);
                      expect(data.problem.contest.created).to.be.a('number');
                  expect(data.problem.contest.created).to.be("0");
                  expect(data.problem.contest.description).to.be.a('string');
                  expect(data.problem.contest.description).to.be("");
                  expect(data.problem.contest.duration).to.be.a('number');
                  expect(data.problem.contest.duration).to.be("0");
                  expect(data.problem.contest.id).to.be.a('number');
                  expect(data.problem.contest.id).to.be("0");
                  expect(data.problem.contest.name).to.be.a('string');
                  expect(data.problem.contest.name).to.be("");
                  expect(data.problem.contest.organizer).to.be.a(AhanaApi.ModelsUser);
                        expect(data.problem.contest.organizer.apiKey).to.be.a('string');
                    expect(data.problem.contest.organizer.apiKey).to.be("");
                    expect(data.problem.contest.organizer.created).to.be.a('number');
                    expect(data.problem.contest.organizer.created).to.be("0");
                    expect(data.problem.contest.organizer.email).to.be.a('string');
                    expect(data.problem.contest.organizer.email).to.be("");
                    expect(data.problem.contest.organizer.emailNotificationEnabled).to.be.a('boolean');
                    expect(data.problem.contest.organizer.emailNotificationEnabled).to.be(false);
                    expect(data.problem.contest.organizer.firebaseUID).to.be.a('string');
                    expect(data.problem.contest.organizer.firebaseUID).to.be("");
                    expect(data.problem.contest.organizer.handle).to.be.a('string');
                    expect(data.problem.contest.organizer.handle).to.be("");
                    expect(data.problem.contest.organizer.id).to.be.a('number');
                    expect(data.problem.contest.organizer.id).to.be("0");
                    expect(data.problem.contest.organizer.isLocked).to.be.a('boolean');
                    expect(data.problem.contest.organizer.isLocked).to.be(false);
                    expect(data.problem.contest.organizer.name).to.be.a('string');
                    expect(data.problem.contest.organizer.name).to.be("");
                    expect(data.problem.contest.organizer.phoneNumber).to.be.a('string');
                    expect(data.problem.contest.organizer.phoneNumber).to.be("");
                    expect(data.problem.contest.organizer.rating).to.be.a('number');
                    expect(data.problem.contest.organizer.rating).to.be("0");
                    expect(data.problem.contest.organizer.signUpMode).to.be.a(AhanaApi.ModelsSignUpMode);
                        expect(data.problem.contest.organizer.tSize).to.be.a('string');
                    expect(data.problem.contest.organizer.tSize).to.be("");
                    expect(data.problem.contest.organizer.type).to.be.a(AhanaApi.ModelsUserType);
                        expect(data.problem.contest.organizer.updated).to.be.a('number');
                    expect(data.problem.contest.organizer.updated).to.be("0");
                  expect(data.problem.contest.series).to.be.a(AhanaApi.ModelsSeries);
                        expect(data.problem.contest.series.created).to.be.a('number');
                    expect(data.problem.contest.series.created).to.be("0");
                    expect(data.problem.contest.series.description).to.be.a('string');
                    expect(data.problem.contest.series.description).to.be("");
                    expect(data.problem.contest.series.id).to.be.a('number');
                    expect(data.problem.contest.series.id).to.be("0");
                    expect(data.problem.contest.series.logoUrl).to.be.a('string');
                    expect(data.problem.contest.series.logoUrl).to.be("");
                    expect(data.problem.contest.series.name).to.be.a('string');
                    expect(data.problem.contest.series.name).to.be("");
                    expect(data.problem.contest.series.updated).to.be.a('number');
                    expect(data.problem.contest.series.updated).to.be("0");
                  expect(data.problem.contest.start).to.be.a('number');
                  expect(data.problem.contest.start).to.be("0");
                  expect(data.problem.contest.updated).to.be.a('number');
                  expect(data.problem.contest.updated).to.be("0");
                expect(data.problem.created).to.be.a('number');
                expect(data.problem.created).to.be("0");
                expect(data.problem.editorial).to.be.a('string');
                expect(data.problem.editorial).to.be("");
                expect(data.problem.id).to.be.a('number');
                expect(data.problem.id).to.be("0");
                expect(data.problem.inputFormat).to.be.a('string');
                expect(data.problem.inputFormat).to.be("");
                expect(data.problem.maxScore).to.be.a('number');
                expect(data.problem.maxScore).to.be("0");
                expect(data.problem.name).to.be.a('string');
                expect(data.problem.name).to.be("");
                expect(data.problem.outputFormat).to.be.a('string');
                expect(data.problem.outputFormat).to.be("");
                expect(data.problem.sampleExplanation).to.be.a('string');
                expect(data.problem.sampleExplanation).to.be("");
                expect(data.problem.sampleInput).to.be.a('string');
                expect(data.problem.sampleInput).to.be("");
                expect(data.problem.sampleOutput).to.be.a('string');
                expect(data.problem.sampleOutput).to.be("");
                expect(data.problem.statement).to.be.a('string');
                expect(data.problem.statement).to.be("");
                expect(data.problem.updated).to.be.a('number');
                expect(data.problem.updated).to.be("0");
              expect(data.type).to.be.a(AhanaApi.ModelsSubmissionType);
                  expect(data.updated).to.be.a('number');
              expect(data.updated).to.be("0");
              expect(data.verdict).to.be.a(AhanaApi.ModelsVerdictType);
      
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('submissionControllerGetSubmission', function() {
        it('should call submissionControllerGetSubmission successfully', function(done) {
          // TODO: uncomment, update parameter values for submissionControllerGetSubmission call and complete the assertions
          /*
          var xUserApiKey = "xUserApiKey_example";
          var submissionId = 789;

          instance.submissionControllerGetSubmission(xUserApiKey, submissionId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AhanaApi.ModelsSubmission);
            expect(data.contest).to.be.a(AhanaApi.ModelsContest);
                  expect(data.contest.created).to.be.a('number');
              expect(data.contest.created).to.be("0");
              expect(data.contest.description).to.be.a('string');
              expect(data.contest.description).to.be("");
              expect(data.contest.duration).to.be.a('number');
              expect(data.contest.duration).to.be("0");
              expect(data.contest.id).to.be.a('number');
              expect(data.contest.id).to.be("0");
              expect(data.contest.name).to.be.a('string');
              expect(data.contest.name).to.be("");
              expect(data.contest.organizer).to.be.a(AhanaApi.ModelsUser);
                    expect(data.contest.organizer.apiKey).to.be.a('string');
                expect(data.contest.organizer.apiKey).to.be("");
                expect(data.contest.organizer.created).to.be.a('number');
                expect(data.contest.organizer.created).to.be("0");
                expect(data.contest.organizer.email).to.be.a('string');
                expect(data.contest.organizer.email).to.be("");
                expect(data.contest.organizer.emailNotificationEnabled).to.be.a('boolean');
                expect(data.contest.organizer.emailNotificationEnabled).to.be(false);
                expect(data.contest.organizer.firebaseUID).to.be.a('string');
                expect(data.contest.organizer.firebaseUID).to.be("");
                expect(data.contest.organizer.handle).to.be.a('string');
                expect(data.contest.organizer.handle).to.be("");
                expect(data.contest.organizer.id).to.be.a('number');
                expect(data.contest.organizer.id).to.be("0");
                expect(data.contest.organizer.isLocked).to.be.a('boolean');
                expect(data.contest.organizer.isLocked).to.be(false);
                expect(data.contest.organizer.name).to.be.a('string');
                expect(data.contest.organizer.name).to.be("");
                expect(data.contest.organizer.phoneNumber).to.be.a('string');
                expect(data.contest.organizer.phoneNumber).to.be("");
                expect(data.contest.organizer.rating).to.be.a('number');
                expect(data.contest.organizer.rating).to.be("0");
                expect(data.contest.organizer.signUpMode).to.be.a(AhanaApi.ModelsSignUpMode);
                    expect(data.contest.organizer.tSize).to.be.a('string');
                expect(data.contest.organizer.tSize).to.be("");
                expect(data.contest.organizer.type).to.be.a(AhanaApi.ModelsUserType);
                    expect(data.contest.organizer.updated).to.be.a('number');
                expect(data.contest.organizer.updated).to.be("0");
              expect(data.contest.series).to.be.a(AhanaApi.ModelsSeries);
                    expect(data.contest.series.created).to.be.a('number');
                expect(data.contest.series.created).to.be("0");
                expect(data.contest.series.description).to.be.a('string');
                expect(data.contest.series.description).to.be("");
                expect(data.contest.series.id).to.be.a('number');
                expect(data.contest.series.id).to.be("0");
                expect(data.contest.series.logoUrl).to.be.a('string');
                expect(data.contest.series.logoUrl).to.be("");
                expect(data.contest.series.name).to.be.a('string');
                expect(data.contest.series.name).to.be("");
                expect(data.contest.series.updated).to.be.a('number');
                expect(data.contest.series.updated).to.be("0");
              expect(data.contest.start).to.be.a('number');
              expect(data.contest.start).to.be("0");
              expect(data.contest.updated).to.be.a('number');
              expect(data.contest.updated).to.be("0");
            expect(data.created).to.be.a('number');
            expect(data.created).to.be("0");
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.problem).to.be.a(AhanaApi.ModelsCodingProblem);
                  expect(data.problem.constraints).to.be.a('string');
              expect(data.problem.constraints).to.be("");
              expect(data.problem.contest).to.be.a(AhanaApi.ModelsContest);
                    expect(data.problem.contest.created).to.be.a('number');
                expect(data.problem.contest.created).to.be("0");
                expect(data.problem.contest.description).to.be.a('string');
                expect(data.problem.contest.description).to.be("");
                expect(data.problem.contest.duration).to.be.a('number');
                expect(data.problem.contest.duration).to.be("0");
                expect(data.problem.contest.id).to.be.a('number');
                expect(data.problem.contest.id).to.be("0");
                expect(data.problem.contest.name).to.be.a('string');
                expect(data.problem.contest.name).to.be("");
                expect(data.problem.contest.organizer).to.be.a(AhanaApi.ModelsUser);
                      expect(data.problem.contest.organizer.apiKey).to.be.a('string');
                  expect(data.problem.contest.organizer.apiKey).to.be("");
                  expect(data.problem.contest.organizer.created).to.be.a('number');
                  expect(data.problem.contest.organizer.created).to.be("0");
                  expect(data.problem.contest.organizer.email).to.be.a('string');
                  expect(data.problem.contest.organizer.email).to.be("");
                  expect(data.problem.contest.organizer.emailNotificationEnabled).to.be.a('boolean');
                  expect(data.problem.contest.organizer.emailNotificationEnabled).to.be(false);
                  expect(data.problem.contest.organizer.firebaseUID).to.be.a('string');
                  expect(data.problem.contest.organizer.firebaseUID).to.be("");
                  expect(data.problem.contest.organizer.handle).to.be.a('string');
                  expect(data.problem.contest.organizer.handle).to.be("");
                  expect(data.problem.contest.organizer.id).to.be.a('number');
                  expect(data.problem.contest.organizer.id).to.be("0");
                  expect(data.problem.contest.organizer.isLocked).to.be.a('boolean');
                  expect(data.problem.contest.organizer.isLocked).to.be(false);
                  expect(data.problem.contest.organizer.name).to.be.a('string');
                  expect(data.problem.contest.organizer.name).to.be("");
                  expect(data.problem.contest.organizer.phoneNumber).to.be.a('string');
                  expect(data.problem.contest.organizer.phoneNumber).to.be("");
                  expect(data.problem.contest.organizer.rating).to.be.a('number');
                  expect(data.problem.contest.organizer.rating).to.be("0");
                  expect(data.problem.contest.organizer.signUpMode).to.be.a(AhanaApi.ModelsSignUpMode);
                      expect(data.problem.contest.organizer.tSize).to.be.a('string');
                  expect(data.problem.contest.organizer.tSize).to.be("");
                  expect(data.problem.contest.organizer.type).to.be.a(AhanaApi.ModelsUserType);
                      expect(data.problem.contest.organizer.updated).to.be.a('number');
                  expect(data.problem.contest.organizer.updated).to.be("0");
                expect(data.problem.contest.series).to.be.a(AhanaApi.ModelsSeries);
                      expect(data.problem.contest.series.created).to.be.a('number');
                  expect(data.problem.contest.series.created).to.be("0");
                  expect(data.problem.contest.series.description).to.be.a('string');
                  expect(data.problem.contest.series.description).to.be("");
                  expect(data.problem.contest.series.id).to.be.a('number');
                  expect(data.problem.contest.series.id).to.be("0");
                  expect(data.problem.contest.series.logoUrl).to.be.a('string');
                  expect(data.problem.contest.series.logoUrl).to.be("");
                  expect(data.problem.contest.series.name).to.be.a('string');
                  expect(data.problem.contest.series.name).to.be("");
                  expect(data.problem.contest.series.updated).to.be.a('number');
                  expect(data.problem.contest.series.updated).to.be("0");
                expect(data.problem.contest.start).to.be.a('number');
                expect(data.problem.contest.start).to.be("0");
                expect(data.problem.contest.updated).to.be.a('number');
                expect(data.problem.contest.updated).to.be("0");
              expect(data.problem.created).to.be.a('number');
              expect(data.problem.created).to.be("0");
              expect(data.problem.editorial).to.be.a('string');
              expect(data.problem.editorial).to.be("");
              expect(data.problem.id).to.be.a('number');
              expect(data.problem.id).to.be("0");
              expect(data.problem.inputFormat).to.be.a('string');
              expect(data.problem.inputFormat).to.be("");
              expect(data.problem.maxScore).to.be.a('number');
              expect(data.problem.maxScore).to.be("0");
              expect(data.problem.name).to.be.a('string');
              expect(data.problem.name).to.be("");
              expect(data.problem.outputFormat).to.be.a('string');
              expect(data.problem.outputFormat).to.be("");
              expect(data.problem.sampleExplanation).to.be.a('string');
              expect(data.problem.sampleExplanation).to.be("");
              expect(data.problem.sampleInput).to.be.a('string');
              expect(data.problem.sampleInput).to.be("");
              expect(data.problem.sampleOutput).to.be.a('string');
              expect(data.problem.sampleOutput).to.be("");
              expect(data.problem.statement).to.be.a('string');
              expect(data.problem.statement).to.be("");
              expect(data.problem.updated).to.be.a('number');
              expect(data.problem.updated).to.be("0");
            expect(data.type).to.be.a(AhanaApi.ModelsSubmissionType);
                expect(data.updated).to.be.a('number');
            expect(data.updated).to.be("0");
            expect(data.verdict).to.be.a(AhanaApi.ModelsVerdictType);
    
            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('submissionControllerGetSubmissionDeadlineByProblem', function() {
        it('should call submissionControllerGetSubmissionDeadlineByProblem successfully', function(done) {
          // TODO: uncomment, update parameter values for submissionControllerGetSubmissionDeadlineByProblem call and complete the assertions
          /*
          var xUserApiKey = "xUserApiKey_example";
          var pid = 789;

          instance.submissionControllerGetSubmissionDeadlineByProblem(xUserApiKey, pid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AhanaApi.ModelsRSubmissionDeadline);
            expect(data.inputFileDownloaded).to.be.a('boolean');
            expect(data.inputFileDownloaded).to.be(false);
            expect(data.inputFileUrl).to.be.a('string');
            expect(data.inputFileUrl).to.be("");
            expect(data.submissionDeadline).to.be.a(AhanaApi.ModelsSubmissionDeadline);
                  expect(data.submissionDeadline.contest).to.be.a(AhanaApi.ModelsContest);
                    expect(data.submissionDeadline.contest.created).to.be.a('number');
                expect(data.submissionDeadline.contest.created).to.be("0");
                expect(data.submissionDeadline.contest.description).to.be.a('string');
                expect(data.submissionDeadline.contest.description).to.be("");
                expect(data.submissionDeadline.contest.duration).to.be.a('number');
                expect(data.submissionDeadline.contest.duration).to.be("0");
                expect(data.submissionDeadline.contest.id).to.be.a('number');
                expect(data.submissionDeadline.contest.id).to.be("0");
                expect(data.submissionDeadline.contest.name).to.be.a('string');
                expect(data.submissionDeadline.contest.name).to.be("");
                expect(data.submissionDeadline.contest.organizer).to.be.a(AhanaApi.ModelsUser);
                      expect(data.submissionDeadline.contest.organizer.apiKey).to.be.a('string');
                  expect(data.submissionDeadline.contest.organizer.apiKey).to.be("");
                  expect(data.submissionDeadline.contest.organizer.created).to.be.a('number');
                  expect(data.submissionDeadline.contest.organizer.created).to.be("0");
                  expect(data.submissionDeadline.contest.organizer.email).to.be.a('string');
                  expect(data.submissionDeadline.contest.organizer.email).to.be("");
                  expect(data.submissionDeadline.contest.organizer.emailNotificationEnabled).to.be.a('boolean');
                  expect(data.submissionDeadline.contest.organizer.emailNotificationEnabled).to.be(false);
                  expect(data.submissionDeadline.contest.organizer.firebaseUID).to.be.a('string');
                  expect(data.submissionDeadline.contest.organizer.firebaseUID).to.be("");
                  expect(data.submissionDeadline.contest.organizer.handle).to.be.a('string');
                  expect(data.submissionDeadline.contest.organizer.handle).to.be("");
                  expect(data.submissionDeadline.contest.organizer.id).to.be.a('number');
                  expect(data.submissionDeadline.contest.organizer.id).to.be("0");
                  expect(data.submissionDeadline.contest.organizer.isLocked).to.be.a('boolean');
                  expect(data.submissionDeadline.contest.organizer.isLocked).to.be(false);
                  expect(data.submissionDeadline.contest.organizer.name).to.be.a('string');
                  expect(data.submissionDeadline.contest.organizer.name).to.be("");
                  expect(data.submissionDeadline.contest.organizer.phoneNumber).to.be.a('string');
                  expect(data.submissionDeadline.contest.organizer.phoneNumber).to.be("");
                  expect(data.submissionDeadline.contest.organizer.rating).to.be.a('number');
                  expect(data.submissionDeadline.contest.organizer.rating).to.be("0");
                  expect(data.submissionDeadline.contest.organizer.signUpMode).to.be.a(AhanaApi.ModelsSignUpMode);
                      expect(data.submissionDeadline.contest.organizer.tSize).to.be.a('string');
                  expect(data.submissionDeadline.contest.organizer.tSize).to.be("");
                  expect(data.submissionDeadline.contest.organizer.type).to.be.a(AhanaApi.ModelsUserType);
                      expect(data.submissionDeadline.contest.organizer.updated).to.be.a('number');
                  expect(data.submissionDeadline.contest.organizer.updated).to.be("0");
                expect(data.submissionDeadline.contest.series).to.be.a(AhanaApi.ModelsSeries);
                      expect(data.submissionDeadline.contest.series.created).to.be.a('number');
                  expect(data.submissionDeadline.contest.series.created).to.be("0");
                  expect(data.submissionDeadline.contest.series.description).to.be.a('string');
                  expect(data.submissionDeadline.contest.series.description).to.be("");
                  expect(data.submissionDeadline.contest.series.id).to.be.a('number');
                  expect(data.submissionDeadline.contest.series.id).to.be("0");
                  expect(data.submissionDeadline.contest.series.logoUrl).to.be.a('string');
                  expect(data.submissionDeadline.contest.series.logoUrl).to.be("");
                  expect(data.submissionDeadline.contest.series.name).to.be.a('string');
                  expect(data.submissionDeadline.contest.series.name).to.be("");
                  expect(data.submissionDeadline.contest.series.updated).to.be.a('number');
                  expect(data.submissionDeadline.contest.series.updated).to.be("0");
                expect(data.submissionDeadline.contest.start).to.be.a('number');
                expect(data.submissionDeadline.contest.start).to.be("0");
                expect(data.submissionDeadline.contest.updated).to.be.a('number');
                expect(data.submissionDeadline.contest.updated).to.be("0");
              expect(data.submissionDeadline.created).to.be.a('number');
              expect(data.submissionDeadline.created).to.be("0");
              expect(data.submissionDeadline.deadline).to.be.a('number');
              expect(data.submissionDeadline.deadline).to.be("0");
              expect(data.submissionDeadline.id).to.be.a('number');
              expect(data.submissionDeadline.id).to.be("0");
              expect(data.submissionDeadline.problem).to.be.a(AhanaApi.ModelsCodingProblem);
                    expect(data.submissionDeadline.problem.constraints).to.be.a('string');
                expect(data.submissionDeadline.problem.constraints).to.be("");
                expect(data.submissionDeadline.problem.contest).to.be.a(AhanaApi.ModelsContest);
                      expect(data.submissionDeadline.problem.contest.created).to.be.a('number');
                  expect(data.submissionDeadline.problem.contest.created).to.be("0");
                  expect(data.submissionDeadline.problem.contest.description).to.be.a('string');
                  expect(data.submissionDeadline.problem.contest.description).to.be("");
                  expect(data.submissionDeadline.problem.contest.duration).to.be.a('number');
                  expect(data.submissionDeadline.problem.contest.duration).to.be("0");
                  expect(data.submissionDeadline.problem.contest.id).to.be.a('number');
                  expect(data.submissionDeadline.problem.contest.id).to.be("0");
                  expect(data.submissionDeadline.problem.contest.name).to.be.a('string');
                  expect(data.submissionDeadline.problem.contest.name).to.be("");
                  expect(data.submissionDeadline.problem.contest.organizer).to.be.a(AhanaApi.ModelsUser);
                        expect(data.submissionDeadline.problem.contest.organizer.apiKey).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.organizer.apiKey).to.be("");
                    expect(data.submissionDeadline.problem.contest.organizer.created).to.be.a('number');
                    expect(data.submissionDeadline.problem.contest.organizer.created).to.be("0");
                    expect(data.submissionDeadline.problem.contest.organizer.email).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.organizer.email).to.be("");
                    expect(data.submissionDeadline.problem.contest.organizer.emailNotificationEnabled).to.be.a('boolean');
                    expect(data.submissionDeadline.problem.contest.organizer.emailNotificationEnabled).to.be(false);
                    expect(data.submissionDeadline.problem.contest.organizer.firebaseUID).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.organizer.firebaseUID).to.be("");
                    expect(data.submissionDeadline.problem.contest.organizer.handle).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.organizer.handle).to.be("");
                    expect(data.submissionDeadline.problem.contest.organizer.id).to.be.a('number');
                    expect(data.submissionDeadline.problem.contest.organizer.id).to.be("0");
                    expect(data.submissionDeadline.problem.contest.organizer.isLocked).to.be.a('boolean');
                    expect(data.submissionDeadline.problem.contest.organizer.isLocked).to.be(false);
                    expect(data.submissionDeadline.problem.contest.organizer.name).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.organizer.name).to.be("");
                    expect(data.submissionDeadline.problem.contest.organizer.phoneNumber).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.organizer.phoneNumber).to.be("");
                    expect(data.submissionDeadline.problem.contest.organizer.rating).to.be.a('number');
                    expect(data.submissionDeadline.problem.contest.organizer.rating).to.be("0");
                    expect(data.submissionDeadline.problem.contest.organizer.signUpMode).to.be.a(AhanaApi.ModelsSignUpMode);
                        expect(data.submissionDeadline.problem.contest.organizer.tSize).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.organizer.tSize).to.be("");
                    expect(data.submissionDeadline.problem.contest.organizer.type).to.be.a(AhanaApi.ModelsUserType);
                        expect(data.submissionDeadline.problem.contest.organizer.updated).to.be.a('number');
                    expect(data.submissionDeadline.problem.contest.organizer.updated).to.be("0");
                  expect(data.submissionDeadline.problem.contest.series).to.be.a(AhanaApi.ModelsSeries);
                        expect(data.submissionDeadline.problem.contest.series.created).to.be.a('number');
                    expect(data.submissionDeadline.problem.contest.series.created).to.be("0");
                    expect(data.submissionDeadline.problem.contest.series.description).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.series.description).to.be("");
                    expect(data.submissionDeadline.problem.contest.series.id).to.be.a('number');
                    expect(data.submissionDeadline.problem.contest.series.id).to.be("0");
                    expect(data.submissionDeadline.problem.contest.series.logoUrl).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.series.logoUrl).to.be("");
                    expect(data.submissionDeadline.problem.contest.series.name).to.be.a('string');
                    expect(data.submissionDeadline.problem.contest.series.name).to.be("");
                    expect(data.submissionDeadline.problem.contest.series.updated).to.be.a('number');
                    expect(data.submissionDeadline.problem.contest.series.updated).to.be("0");
                  expect(data.submissionDeadline.problem.contest.start).to.be.a('number');
                  expect(data.submissionDeadline.problem.contest.start).to.be("0");
                  expect(data.submissionDeadline.problem.contest.updated).to.be.a('number');
                  expect(data.submissionDeadline.problem.contest.updated).to.be("0");
                expect(data.submissionDeadline.problem.created).to.be.a('number');
                expect(data.submissionDeadline.problem.created).to.be("0");
                expect(data.submissionDeadline.problem.editorial).to.be.a('string');
                expect(data.submissionDeadline.problem.editorial).to.be("");
                expect(data.submissionDeadline.problem.id).to.be.a('number');
                expect(data.submissionDeadline.problem.id).to.be("0");
                expect(data.submissionDeadline.problem.inputFormat).to.be.a('string');
                expect(data.submissionDeadline.problem.inputFormat).to.be("");
                expect(data.submissionDeadline.problem.maxScore).to.be.a('number');
                expect(data.submissionDeadline.problem.maxScore).to.be("0");
                expect(data.submissionDeadline.problem.name).to.be.a('string');
                expect(data.submissionDeadline.problem.name).to.be("");
                expect(data.submissionDeadline.problem.outputFormat).to.be.a('string');
                expect(data.submissionDeadline.problem.outputFormat).to.be("");
                expect(data.submissionDeadline.problem.sampleExplanation).to.be.a('string');
                expect(data.submissionDeadline.problem.sampleExplanation).to.be("");
                expect(data.submissionDeadline.problem.sampleInput).to.be.a('string');
                expect(data.submissionDeadline.problem.sampleInput).to.be("");
                expect(data.submissionDeadline.problem.sampleOutput).to.be.a('string');
                expect(data.submissionDeadline.problem.sampleOutput).to.be("");
                expect(data.submissionDeadline.problem.statement).to.be.a('string');
                expect(data.submissionDeadline.problem.statement).to.be("");
                expect(data.submissionDeadline.problem.updated).to.be.a('number');
                expect(data.submissionDeadline.problem.updated).to.be("0");
              expect(data.submissionDeadline.updated).to.be.a('number');
              expect(data.submissionDeadline.updated).to.be("0");
              expect(data.submissionDeadline.user).to.be.a(AhanaApi.ModelsUser);
                    expect(data.submissionDeadline.user.apiKey).to.be.a('string');
                expect(data.submissionDeadline.user.apiKey).to.be("");
                expect(data.submissionDeadline.user.created).to.be.a('number');
                expect(data.submissionDeadline.user.created).to.be("0");
                expect(data.submissionDeadline.user.email).to.be.a('string');
                expect(data.submissionDeadline.user.email).to.be("");
                expect(data.submissionDeadline.user.emailNotificationEnabled).to.be.a('boolean');
                expect(data.submissionDeadline.user.emailNotificationEnabled).to.be(false);
                expect(data.submissionDeadline.user.firebaseUID).to.be.a('string');
                expect(data.submissionDeadline.user.firebaseUID).to.be("");
                expect(data.submissionDeadline.user.handle).to.be.a('string');
                expect(data.submissionDeadline.user.handle).to.be("");
                expect(data.submissionDeadline.user.id).to.be.a('number');
                expect(data.submissionDeadline.user.id).to.be("0");
                expect(data.submissionDeadline.user.isLocked).to.be.a('boolean');
                expect(data.submissionDeadline.user.isLocked).to.be(false);
                expect(data.submissionDeadline.user.name).to.be.a('string');
                expect(data.submissionDeadline.user.name).to.be("");
                expect(data.submissionDeadline.user.phoneNumber).to.be.a('string');
                expect(data.submissionDeadline.user.phoneNumber).to.be("");
                expect(data.submissionDeadline.user.rating).to.be.a('number');
                expect(data.submissionDeadline.user.rating).to.be("0");
                expect(data.submissionDeadline.user.signUpMode).to.be.a(AhanaApi.ModelsSignUpMode);
                    expect(data.submissionDeadline.user.tSize).to.be.a('string');
                expect(data.submissionDeadline.user.tSize).to.be("");
                expect(data.submissionDeadline.user.type).to.be.a(AhanaApi.ModelsUserType);
                    expect(data.submissionDeadline.user.updated).to.be.a('number');
                expect(data.submissionDeadline.user.updated).to.be("0");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('submissionControllerSubmitCodeSolution', function() {
        it('should call submissionControllerSubmitCodeSolution successfully', function(done) {
          // TODO: uncomment, update parameter values for submissionControllerSubmitCodeSolution call and complete the assertions
          /*
          var xUserApiKey = "xUserApiKey_example";
          var contestId = 789;
          var problemId = 789;
          var sfile = "/path/to/file.txt";
          var cfile = "/path/to/file.txt";

          instance.submissionControllerSubmitCodeSolution(xUserApiKey, contestId, problemId, sfile, cfile, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(AhanaApi.ModelsSubmissionResponse);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");
            expect(data.verdict).to.be.a('string');
            expect(data.verdict).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
